name: "generate-multi-source-snake-animation"
description: "Can generate multisource snake animation from both GitHub and Gitee"
author: "ZQ"

runs:
  using: docker
  image: docker://pray0/multi-source-snake:v1.2

inputs:
  GITHUB_USER:
    description: "GitHub user name"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token used to fetch the contribution calendar. Default to the action token if empty."
    required: true
  GITEE_USER:
    description: "Gitee user name"
    required: true
  GITEE_TOKEN:
    description: "Gitee token used to access Gitee API."
    required: true

